Title = "Watch Dsut"

# 미세먼지 파악(알림) 간격
WatchIntervalHour = 3

[openapi_airkorea]
# 서비스키
servicekey = ""
# 한 페이지 결과 수
numOfRows = 10
# 페이지 번호
pageNo = 1
# 측정소 이름
stationName = "수내동"
# 요청 데이터기간 (하루 : DAILY, 한달 : MONTH, 3달 : 3MONTH)
dataTerm = "DAILY"
# 버전별 상세 결과 참고문서 참조
ver = "1.3"


[slack_api]
# 토큰
token = ""
# 메시지 보낼 채널
channel = "dustinfo"
# 봇이름
username = "watchDust bot"
